#!/bin/sh

sflag=
while getopts s opt; do
	case $opt in
	s) sflag=1 ;;
	*)
		printf "usage: %s [-s]\n" "$0" >&2
		exit 1
		;;
	esac
done

cat <<'EOF'
Booting oasis qemu image...

Tips:
- To access the qemu console, use Ctrl-a c.
- The root password is empty.
- A regular user 'oasis' is available, also with empty password.
- To run commands as root, use doas(1)
- Text editors available are vis(1) and ed(1)
- To launch velox, run `swc-launch velox`.
  * To launch st from velox, use Alt-Shift-Enter
  * To launch netsurf from velox, use Alt-b
  * To launch dmenu from velox, use Alt-r
- To shutdown, run `kill -s USR1 1`.

See README.md for more information.

EOF

append='init=/bin/sinit root=/dev/vda ro'

if [ -n "$sflag" ]; then
	append="$append console=hvc0"
	set -- \
		-chardev stdio,id=cons,mux=on,signal=off \
		-device virtconsole,chardev=cons \
		-display none \
		"$@"
else
	set -- \
		-chardev stdio,id=cons \
		-device virtio-keyboard \
		-device virtio-tablet \
		-device virtio-vga \
		"$@"
fi

exec qemu-system-x86_64 \
	-enable-kvm -cpu host -m 2048 \
	-kernel bzImage \
	-append "$append" \
	-device virtio-balloon \
	-device virtio-rng \
	-device virtio-serial \
	-drive file=root.qcow2,media=disk,if=virtio \
	-nic user,model=virtio \
	-mon chardev=cons \
	"$@"
