#!/bin/sh

cat message.txt

exec qemu-system-x86_64 \
	-enable-kvm -cpu host -m 2048 \
	-kernel bzImage \
	-append 'init=/bin/sinit root=/dev/vda console=hvc0 ro' \
	-device virtio-balloon \
	-device virtio-rng \
	-device virtio-serial \
	-drive file=root.qcow2,media=disk,if=virtio \
	-nic user,model=virtio \
	-chardev stdio,id=cons,mux=on,signal=off \
	-device virtconsole,chardev=cons \
	-mon chardev=cons \
	-display none
