#!/bin/sh

cat message.txt

exec qemu-system-x86_64 \
	-enable-kvm -cpu host -m 2048 \
	-kernel bzImage \
	-append 'init=/bin/sinit root=/dev/vda ro' \
	-device virtio-balloon \
	-device virtio-rng \
	-device virtio-serial \
	-device virtio-keyboard \
	-device virtio-tablet \
	-device virtio-vga \
	-drive file=root.qcow2,media=disk,if=virtio \
	-nic user,model=virtio \
	-chardev stdio,id=cons \
	-mon chardev=cons
